# Generated by Django 5.1.4 on 2025-05-16 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_tipo_asistencia'),
        ('users', '0006_tipoasistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tipo_asistencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_asistencias', to='users.tipoasistencia'),
        ),
    ]
