# Generated by Django 5.1.4 on 2025-01-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_add_admin',
            field=models.BooleanField(default=False),
        ),
    ]
