# Generated by Django 5.1.4 on 2025-01-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_can_add_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('client', 'Cliente'), ('technician', 'Técnico'), ('admin', 'Administrador')], default='client', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
    ]
