# Generated by Django 5.1.4 on 2025-02-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_role_alter_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='estado_conexion',
            field=models.CharField(choices=[('online', 'En Línea'), ('offline', 'Fuera de Línea')], default='offline', max_length=10),
        ),
    ]
