# Generated by Django 5.1.4 on 2025-05-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_created_at_userprofile_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_asistencia', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('open', 'Activo'), ('closed', 'Eliminado')], default='open', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Asistencia',
                'verbose_name_plural': 'Tipos de Asistencia',
                'db_table': 'users_asistencia',
                'ordering': ['tipo_asistencia'],
            },
        ),
    ]
