# Generated by Django 5.1.4 on 2025-05-16 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_created_at_userprofile_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=100)),
                ('estadoCategoria', models.BooleanField(default=True)),
                ('fechaCreacionCategoria', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacionCategoria', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('idMetodoPago', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMetodo', models.CharField(max_length=100)),
                ('descripcionMetodo', models.TextField()),
                ('estadoMetodoPago', models.BooleanField(default=True)),
                ('fechaCreacionPago', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacionPago', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('idTipoComprobante', models.AutoField(primary_key=True, serialize=False)),
                ('nombreComprobante', models.CharField(max_length=100)),
                ('estadoComprobante', models.BooleanField(default=True)),
                ('fechaCreacionComprobante', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacionComprobante', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('idUbicacion', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.TextField()),
                ('tiempoEstimadoEntrega', models.IntegerField(help_text='Tiempo en días')),
                ('estadoUbicacion', models.BooleanField(default=True)),
                ('fechaCreacionUbicacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacionUbicacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=200)),
                ('descripcionProducto', models.TextField()),
                ('stock', models.IntegerField(default=0)),
                ('precioVenta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precioCompra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estadoProducto', models.BooleanField(default=True)),
                ('fechaCaducidad', models.DateField(blank=True, null=True)),
                ('fechaCreacionProducto', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacionProducto', models.DateTimeField(auto_now=True)),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idCarrito', models.AutoField(primary_key=True, serialize=False)),
                ('precioConImpuesto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidadSeleccionada', models.IntegerField(default=0)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.producto')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroVenta',
            fields=[
                ('idRegistroVenta', models.AutoField(primary_key=True, serialize=False)),
                ('serieVenta', models.CharField(max_length=50)),
                ('numVenta', models.CharField(max_length=50)),
                ('horaVenta', models.TimeField(auto_now_add=True)),
                ('igv', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('numCuotas', models.IntegerField(default=1)),
                ('subTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('totalVenta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estadoVenta', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fechaCreacionVenta', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacionVenta', models.DateTimeField(auto_now=True)),
                ('idMetodoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.metodopago')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idTipoComprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tipocomprobante')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('idDetalleVenta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precioTotalProducto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.producto')),
                ('idRegistroVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.registroventa')),
            ],
        ),
        migrations.CreateModel(
            name='CompraRecurrente',
            fields=[
                ('idCompraRecurrente', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadComprado', models.IntegerField(default=1)),
                ('nombreCompra', models.CharField(max_length=200)),
                ('fechaCreacionRecurrente', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacionRecurrente', models.DateTimeField(auto_now=True)),
                ('idRegistroVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.registroventa')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('idEntrega', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPreparado', models.DateTimeField(blank=True, null=True)),
                ('fechaEntrega', models.DateTimeField(blank=True, null=True)),
                ('estadoEntrega', models.CharField(choices=[('preparado', 'Preparado'), ('en_camino', 'En Camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='preparado', max_length=20)),
                ('idRegistroVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.registroventa')),
                ('idUbicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ubicacion')),
            ],
        ),
    ]
