# Generated by Django 5.1.4 on 2025-05-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_categoria_metodopago_tipocomprobante_ubicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagenProducto',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
