# Generated by Django 5.1.4 on 2025-06-06 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_producto_imagenproducto'),
        ('users', '0007_user_telefono_alter_userprofile_photo'),
    ]

    operations = [
    ]
