# Generated by Django 5.1.4 on 2025-05-30 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(code='invalid_telefono', message='El teléfono debe tener 9 dígitos, empezar con 9 y no contener letras.', regex='^9\\d{8}$')]),
        ),
    ]
