# Generated by Django 5.1.4 on 2025-06-08 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20250605_2309'),
        ('users', '0010_alter_user_telefono'),
    ]

    operations = [
    ]
