# Generated by Django 5.1.4 on 2025-01-20 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage', models.CharField(max_length=10)),
                ('ram_total', models.CharField(max_length=20)),
                ('ram_used', models.CharField(max_length=20)),
                ('ram_percent', models.CharField(max_length=10)),
                ('disk_total', models.CharField(max_length=20)),
                ('disk_used', models.CharField(max_length=20)),
                ('disk_free', models.CharField(max_length=20)),
                ('disk_percent', models.CharField(max_length=10)),
                ('gpu_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gpu_usage', models.CharField(blank=True, max_length=10, null=True)),
                ('gpu_temperature', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
