# Generated by Django 5.1.4 on 2025-01-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título del Video')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('youtube_url', models.URLField(verbose_name='URL de YouTube')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
