# Generated by Django 5.1.4 on 2025-05-04 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_learningvideo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='fa-solid fa-laptop-code', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='cpu_cores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='cpu_speed',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='cpu_temp',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='disk_health',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='disk_model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='disk_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='gpu_driver',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='gpu_memory',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='issues_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='network_adapter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='network_recv',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='network_sent',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='network_speed',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='os_build',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='os_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='os_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='overall_status',
            field=models.CharField(default='Normal', max_length=20),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='ram_speed',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='ram_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='scan_type',
            field=models.CharField(default='QuickScan', max_length=20),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='warnings_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DiagnosticIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=100)),
                ('issue_type', models.CharField(choices=[('HARDWARE', 'Hardware'), ('DRIVER', 'Controlador'), ('SOFTWARE', 'Software'), ('SECURITY', 'Seguridad'), ('PERFORMANCE', 'Rendimiento'), ('OTHER', 'Otro')], default='OTHER', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=20)),
                ('description', models.TextField()),
                ('recommendation', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='dashboard.diagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Pendiente', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('current_component', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='dashboard.diagnosis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('device', models.CharField(max_length=200)),
                ('current_version', models.CharField(max_length=50)),
                ('latest_version', models.CharField(blank=True, max_length=50, null=True)),
                ('date_installed', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPDATED', 'Actualizado'), ('OUTDATED', 'Desactualizado'), ('MISSING', 'Faltante'), ('INCOMPATIBLE', 'Incompatible'), ('UNKNOWN', 'Desconocido')], default='UNKNOWN', max_length=20)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='dashboard.diagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('results', models.JSONField(default=dict)),
                ('issues_found', models.IntegerField(default=0)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.diagnosticscenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CPU', 'Procesador'), ('RAM', 'Memoria RAM'), ('DISK', 'Disco duro'), ('NETWORK', 'Red'), ('GPU', 'Tarjeta gráfica'), ('BATTERY', 'Batería'), ('ADAPTER', 'Adaptador'), ('DRIVER', 'Controlador'), ('SOFTWARE', 'Software'), ('SECURITY', 'Seguridad'), ('OTHER', 'Otro')], default='OTHER', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('WARNING', 'Advertencia'), ('CRITICAL', 'Crítico'), ('ERROR', 'Error'), ('UNKNOWN', 'Desconocido')], default='UNKNOWN', max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='dashboard.diagnosticreport')),
            ],
        ),
    ]
