# Generated by Django 5.1.4 on 2025-05-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_diagnosticscenario_diagnosis_cpu_cores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='gpu_model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
