# Generated by Django 5.1.4 on 2025-05-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_diagnosis_gpu_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='scan_type',
            field=models.CharField(default='QuickScan', max_length=100),
        ),
    ]
