# Generated by Django 5.1.4 on 2025-05-10 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_diagnosis_scan_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=512)),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dashboard.diagnosis')),
            ],
        ),
    ]
