# Generated by Django 5.1.4 on 2025-05-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_diagnosticfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='scan_type',
            field=models.CharField(default='QuickScan', max_length=150),
        ),
    ]
